int _isupper(int ch);
int _isdigit(int ch);
int mul(long int a, long int b);
int _putchar(int ch);
void print_numbers(void);
void print_most_numbers(void);
void more_numbers(void);
void print_line(int n);
void print_diagonal(int n);
void print_square(int size);
